<Project Sdk="Microsoft.Build.NoTargets">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageProjectReference Include="..\IKVM.Extensions.Logging.Java.Util\IKVM.Extensions.Logging.Java.Util.csproj">
            <PackageTargetPath>.</PackageTargetPath>
        </PackageProjectReference>
    </ItemGroup>

</Project>
